pockethost/pockethost

- .gitignore
- packages/pockethost.io/.gitignore
- readme.md
Created a fork of the pockethost project and setting up some new files.
- `.idea` is a folder created by my Webstorm IDE
- Fixed little thing in the Readme just as a test
If this is all successful, I'll create new branches through the fork like `ui/homepage-design`
> Testing the new UI flow using a fork

- packages/pockethost.io/src/components/Navbar.svelte
> Removed placeholder links

- packages/pockethost.io/src/routes/dashboard/+page.svelte
Added css classes for tablet mode on the Dashboard
> #14 Fixed Dashboard Responsiveness

- packages/common/src/assert.ts
- packages/pockethost.io/package.json
- packages/pockethost.io/src/components/ThemeToggle.svelte
- packages/pockethost.io/src/routes/+layout.svelte
- packages/pockethost.io/src/util/CleanupManager.ts
- yarn.lock
Fixes #32 
@brewhousedigital Please take a look, let me know what you think?
https://user-images.githubusercontent.com/1068356/198077715-7e63f38a-1b95-45e3-987b-2624ca24d20e.mp4
> Darkmode cookie fix

- packages/pockethost.io/src/components/Navbar.svelte
- packages/pockethost.io/src/components/ThemeToggle.svelte
Added new "Discussions" button to the nav bar.
Increased the spacing between nav items on mobile
Fixed bug with the theme icon aligning to the left on mobile
> #36 Added Discussions button to the nav

- packages/pockethost.io/src/routes/app/instances/[instanceId]/Danger/Rename.svelte
> Fix help link in rename instance section

- packages/daemon/src/services/InstanceService/InstanceService.ts
- packages/pockethost.io/src/routes/app/instances/[instanceId]/Danger/Maintenance.svelte
- packages/pockethost.io/src/routes/app/instances/[instanceId]/Version.svelte
Fixed a few broken documentation links throughout the project. Related to #239
> fix broken documentation links

- packages/www/README.md
- packages/www/_includes/components/header.njk
- packages/www/_includes/components/postslist.njk
- packages/www/_includes/layouts/base.njk
- packages/www/_includes/layouts/docs.njk
- packages/www/_includes/layouts/post.njk
- packages/www/content/about/index.md
- packages/www/content/blog.njk
- packages/www/content/docs/introduction.md
- packages/www/content/index.njk
- packages/www/content/tags.njk
- Wrote the entire Readme.md file to show how to create variables, reusable components.
- Included helpful links on the tools used in the project
- Added a whole section for advanced 11ty concepts
- Added the mobile nav
- Homepage now scales better to tablet and mobile view
- Updated the docs template to be more responsive
- Updated the blog template to be more responsive
> Marketing Responsive Improvements

- packages/dashboard/src/app.html
- packages/dashboard/src/components/MobileNavDrawer.svelte
- packages/dashboard/src/components/Navbar.svelte
- packages/dashboard/src/components/cards/Card.svelte
- packages/dashboard/src/components/cards/CardHeader.svelte
- packages/dashboard/src/routes/+layout.svelte
- packages/dashboard/src/routes/app/instances/[instanceId]/+layout.svelte
- packages/dashboard/src/routes/app/instances/[instanceId]/+page.svelte
- packages/dashboard/src/routes/app/instances/[instanceId]/Danger/RenameInstance.svelte
- packages/dashboard/src/routes/app/instances/[instanceId]/Danger/VersionChange.svelte
- packages/dashboard/src/routes/dashboard/InstanceList.svelte
- Added responsive styling to the dashboard
- Added responsive styling to the Instance view
- Added a new Mobile Navigation bar
> Dashboard Responsive Improvements

- packages/dashboard/src/components/Navbar.svelte
- packages/dashboard/src/routes/app/new/+page.svelte
- Designed the new Add App page
- Added new link to the navbar
> Dashboard - Add New App Page

- packages/www/_includes/layouts/base.njk
- Added new "return to top" button that sits in the bottom right corner of the site
- Will scroll users up to the top of the page when clicked
> Marketing - Return To Top Button

- packages/dashboard/src/components/Navbar.svelte
- packages/dashboard/src/components/VerifyAccountBar.svelte
- packages/dashboard/src/routes/+layout.svelte
- packages/dashboard/src/routes/dashboard/+page.svelte
- Added new icon to the sidebar to denote when an instance is in maintenance mode
- Styled the "Confirm Account" banner. Missed that in my initial redesign
> Dashboard - Sidebar Maintenance & Confirm Account Banner

- src/services/InstanceService/index.ts
I noticed this during one of the errors. Minor typo
> App - Minor Typo Fix

- frontends/dashboard/package.json
- frontends/dashboard/src/routes/app/instances/[instanceId]/+layout.svelte
- frontends/dashboard/tailwind.config.cjs
- pnpm-lock.yaml
- Added spacing around the tab system to match the rest of the grid system
- Updated DaisyUI to the latest version
- UX Update - Changed the tabs to look more like "tabs" instead of buttons
> Updated the tab system on the instance screen

- frontends/dashboard/src/components/tables/pricing-table/PricingTable.svelte
- frontends/dashboard/src/routes/account/+page.svelte
Bug I fixed: I'm an annual subscriber that's also a founder. The PricingCard and PricingTables were highlighting and signalling that I am a Pro subscriber but not a founder. I was expecting that the founder card would be highlighted. 
Fix: I simply corrected the logic regarding a premium user and whether or not they are a founder.
> fixed PricingCard styling for Premium + Founder users

- readme.md
> Fix minor typos in README.md

- frontends/dashboard/src/routes/app/instances/[instanceId]/logs/LoggingInner.svelte
Added The Ability for the log to scroll to the newest lines as they come in both the regular and modal forms. As well as added a toggle to both items to allow users to disable this feature.
// Changes
Update LoggingInner.svelte
> AutoScrolling Logs

- frontends/dashboard/src/components/sidebar/SidebarNavLink.svelte
- frontends/dashboard/src/routes/app/instances/[instanceId]/+layout.svelte
1. Sidebar Nav Item Not Staying highlighted when not on overview. 
2. Overview Information not updating when switching between instances.
> Fixed Two Bugs on Dashboard

- docs/hosting/overview.md
- docs/introduction.md
- Removed chat gpt share discussion
- Added a redirect to pockethost
- Fixed typos
> removed broken link, fixed typos, added more styling

- .rizzdown/blog/subject.md
- .rizzdown/docs/subject.md
- .rizzdown/release/subject.md
- frontends/lander/content/docs/overview/introduction.md
> Fixed "could computing" typo to "cloud computing"

- frontends/lander/content/blog/pocket-host-v0-11-0.md
The rizzdown anchor link is invalid, so i fixed it.
> fix: broken blog post anchor link 

- frontends/lander/content/docs/usage/custom-domain.md
Update doc to mention setting in the dashboard for custom domain and this is a paid plan feature https://pockethost.io/docs/usage/custom-domain/
> chore(doc): mention custom domain setting in dashboard

- packages/dashboard/src/routes/(static)/docs/getting-started/+page.md
> Fix 404 link on Getting Started doc page

- packages/dashboard/src/routes/(static)/get-started/RegisterForm.svelte
Fixed the error of entering a blank name instead of entering a name on the registration page.
> Fixed bug.

- packages/dashboard/src/routes/(static)/docs/+page.md
> Removed free wording from docs page

- packages/dashboard/src/routes/+layout.svelte
> get current year
